### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mattben** [CDAT/vcdat#107]
- [x] [building vcs-widgets](https://github.com/UV-CDAT/vcdat/wiki/Building-vcs-widgets)
- [x] [linking vcs-widgets](https://github.com/UV-CDAT/vcdat/wiki/Linking-vcs-widgets)
- [x] [updating vcdat](https://github.com/UV-CDAT/vcdat/wiki/Updating-vCDAT) 
- [x] [deploying vcdat](https://github.com/UV-CDAT/vcdat/wiki/Deploying-vcdat)
- [x] [project basics](https://github.com/UV-CDAT/vcdat/wiki) (npm, react, redux, flask, vcs…)
- [x] [Testing](https://github.com/UV-CDAT/vcdat/wiki/Testing)
- [x] [vCDAT](https://github.com/UV-CDAT/vcdat/wiki/vCDAT) 
- [x] [VCS-Widgets](https://github.com/UV-CDAT/vcdat/wiki/vcs-widgets) 
- [x] [VCS.js](https://github.com/UV-CDAT/vcdat/wiki/VCS.js)
- [ ] [Brain dump](https://github.com/UV-CDAT/vcdat/wiki/Sam's-Notes)

**Comment by James-Crean** [comment]
Documentation is now [here](https://cdat.github.io/vcdat/)
