### ISSUE TITLE
vCDAT ubuntu image size error

### ISSUE THREAD

**Issue by mattben** [CDAT/vcdat#187]
vCDAT running on ubuntu receives images back that are twice the size they should be. This error does not appear on mac.

**Comment by danlipsa** [comment]
As @doutriaux1 pointed out this might be related to how mac laptops expose their increase dpi.
See the following issues for more details:

https://github.com/UV-CDAT/vcs/issues/212

**Comment by James-Crean** [comment]
@doutriaux1 @danlipsa and @scottwittenburg 

Is there a workaround for this? It renders vCDAT completely broken for a subset of users, so we will need a robust fix sooner rather than later.

**Comment by scottwittenburg** [comment]
I'm running vcdat on ubuntu and this does not happen for me.  I can inspect the div where the images are to be placed, look at the websocket frames making the requests and getting the responses, and as far as I can see, the image size matches what was requested.  

Do you have some more information that could possibly help us track this down?

**Comment by James-Crean** [comment]
What might be useful to know for you?

I have asked for the following so far:
* The Ubuntu version
* Output from running conda list v
* Output from running lspci | grep -i 'vga\|3d\|2d'
* The make and model of your screen

**Comment by scottwittenburg** [comment]
I did not understand that it was not you having this problem, but another person.  I was hoping we might have even been able to get together to do some live debugging.  As this sounds like one of your users I guess that's not possible.  

So another piece of information that could be useful is the output from `glxinfo`.  Then it would be good to know how this manifests itself.  Does the user see 1/4 of a giant image (cropped for example)?  How do they know the image is twice the size it should be?  Knowing how they verify this may be helpful.

**Comment by James-Crean** [comment]
```
(2.12-nox) potter@jerry-Lenovo:~$ glxinfo
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_libglvnd, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_INTEL_swap_event, 
    GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, GLX_SGIS_multisample, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, 
    GLX_SGI_make_current_read, GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_create_context_es_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NV137 (0x1cb2)
    Version: 17.2.4
    Accelerated: yes
    Video memory: 2011MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1




(vcdat) potter@jerry-Lenovo:~$ conda list v
# packages in environment at /home/potter/anaconda2/envs/vcdat:
#
# Name                    Version                   Build  Channel
dv3d                      2.12.2017.11.16.13.59.41777804f6a49b899252e8c8a730ce137f501454  py27h3d159b9_0    uvcdat/label/nightly
libiconv                  1.15                          0    conda-forge
vcdat                     0.0.5.2018.02.21.19.37.g764c228            py_0    uvcdat/label/nightly
vcdat                     0.0.5                     <pip>
vcs                       2.12.2018.02.22.03.58.gb56eef02          py27_0    uvcdat/label/nightly
vcs-js                    0.4.2.12.2018.01.31.17.24.7a79ab7847d1c4826263426e39ae68dbc29783ae          py27_0    uvcdat/label/nightly
vtk-cdat                  7.1.0.2.12       py27hd6333ce_0    uvcdat
(vcdat) potter@jerry-Lenovo:~$ 


Samsung 28" monitor

01:00.0 VGA compatible controller: NVIDIA Corporation GP107GL [Quadro P600] (rev a1)
```

**Comment by mattben** [comment]
![screenshot from 2018-03-19 10-33-46](https://user-images.githubusercontent.com/438922/37612037-3daffad8-2b61-11e8-9ae4-78a82fc45065.png)
What other information would you like?

```
You are logged into a Linux Machine...(Version 4.13.0-37-generic)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
4.13.0-37-generic
BashVersion: 4.3
Host: cayde6
Hardware: x86_64....
Machine uptime:
 10:35:34 up 5 days,  3:38,  1 user,  load average: 0.93, 0.82, 0.50
```

**Comment by scottwittenburg** [comment]
Thanks for the info.  Is a hangout within the realm of possibilities so we can do some debugging?  It would be nice to run the application in Chrome during that debugging session as well, so we can look at the websocket frames that are getting sent and received.  Let me know what you think.

**Comment by mattben** [comment]
Thanks @scottwittenburg 

We have determined it is a driver issues. Original `glxinfo` was showing I was using the basic CPU GPU

    direct rendering: Yes
    server glx vendor string: SGI
    server glx version string: 1.4
    ...
    OpenGL renderer string: NVE7
    OpenGL core profile version string: 4.3 (Core Profile) Mesa 17.2.8
    OpenGL core profile shading language version string: 4.30

I installed the nvidia-384 driver package and restarted my computer. Now `glxinfo` shows

    direct rendering: Yes
    server glx vendor string: NVIDIA Corporation 
    server glx version string: 1.4
    ... 
    OpenGL renderer string: Quadro K420/PCIe/SSE2
    OpenGL core profile version string: 4.5.0 NVIDIA 384.111
    OpenGL core profile shading language version string: 4.50 NVIDIA

And vCDAT now works as expected. We either need documentation on how to update video drivers and or some way to decided if a mesa-vcs version is required.

**Comment by James-Crean** [comment]
Troubleshooting docs now instruct users to update their video drivers, or install mesa-lib. Considering this closed unless this bug survives those suggestions.
