### ISSUE TITLE
Remove favorites

### ISSUE THREAD

**Issue by James-Crean** [CDAT/vcdat#200]
Need a way to remove a favorited file from the cached files modal.

**Comment by mattben** [comment]
@James-Crean take a look at this Section #1, maybe we should be using IDs not classes to stop the any draggable being able to drop on any dropable 
https://blog.kevinchisholm.com/html5-javascript/getting-started-with-html5-drag-and-drop-part-iv-multiple-draggables-and-multiple-droppables/
