### ISSUE TITLE
Headless server installation

### ISSUE THREAD

**Issue by James-Crean** [CDAT/vcdat#283]
Installing vcdat on a headless server seems to cause a variety of problems. We need to solve issues that users are encountering, deploy automatic fixes and possibly add some flags that can be set, as well as document any problems that can not be detected and fixed automatically.

**Comment by doutriaux1** [comment]
adding `mesalib` to the env should help greatly. Did you try it?

**Comment by James-Crean** [comment]
Updated installation docs, updated troubleshooting docs and added some additional features to aid debugging.

Will consider this fixed. New installation problems should open new issues for each specific problem.
