### ISSUE TITLE
Help Buttons

### ISSUE THREAD

**Issue by James-Crean** [CDAT/vcdat#320]
We should consider adding help buttons to the more complex components to give users some interactive help and/or tutorials. 

Good candidates for help buttons:

- [x] Calculator
- [x] Load Variable
- [x] Colormap Editor
- [ ] Graphics Method Editors
- [ ] Template Editor
 

The package we currently use for this is React Joyride: http://gilbarbara.github.io/react-joyride/

For a vcdat example of how this works check out the [App Container Component](https://github.com/CDAT/vcdat/blob/master/frontend/src/js/containers/AppContainer.jsx), which has a joyride component, as well as the [Constants.js](https://github.com/CDAT/vcdat/blob/master/frontend/src/js/constants/Constants.js) file that holds the tour text.

**Comment by doutriaux1** [comment]
@downiec this might be a good entry point for you.

**Comment by doutriaux1** [comment]
@sterlingbaldwin it's likely @downiec will need your help at first.
