### ISSUE TITLE
Export plot as PNG

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/vcdat#322]
The plots need to be able to be exported and downloadable by the end user.

**Comment by James-Crean** [comment]
See: https://github.com/CDAT/vcs-js/pull/54

**Comment by sterlingbaldwin** [comment]
Thanks James. The fact that this project is spread over at least 3 repos does not make keeping track of things easy. Also, get off my lawn *shakes fist*

**Comment by sterlingbaldwin** [comment]
I just tried to save a plot with the latest vcdat, after putting in a file name and selecting the file type (svg), I hit save. Nothing appeared to happen, and after searching my computer I couldnt find anything matching the file name I selected. I hit the save button a couple more times for good measure which crashed firefox.

**Comment by downiec** [comment]
I just tested that scenario (made a plot, put in a file name and clicked svg type and saved on firefox) and it is working fine for me. Did you use a new conda environment/fresh install? What kind of file did you plot? I will need more info to see why it's not working for you

**Comment by sterlingbaldwin** [comment]
maybe my firefox just wigged out and died on its own.

**Comment by sterlingbaldwin** [comment]
I was running vcdat and trying to recreate the issue. It didnt crash for me, but I found that if you mutate the data in any way and then save the plot, the original data is plotted instead of the current state. For example, I loaded a variable averaged over the latitudinal axes, but when I saved the plot the png was of the default axes.

**Comment by doutriaux1** [comment]
@scottwittenburg can you take a look please if you have time.

**Comment by doutriaux1** [comment]
thanks @sterlingbaldwin

**Comment by downiec** [comment]
I believed I fixed this issue with my latest update. The export plot png should now match what's seen in the plot.
